window.timorDemoData = {
  processStages: [
    {
      name: "BOOKING FEE",
      state: "완료",
      status: "complete",
      progress: 100,
      date: "2025.10.30 완료",
      guide: "예약금 접수와 계약자 정보 확인이 완료되었습니다.",
      dueAmount: 0,
      paidAmount: 0,
      paymentStatus: "납입 완료",
    },
    {
      name: "8주 이내 계약금",
      state: "완료",
      status: "complete",
      progress: 100,
      date: "2025.11.28 완료",
      guide: "계약금 납입과 공급계약서 확인이 완료되었습니다.",
      dueAmount: 64000000,
      paidAmount: 64000000,
      paymentStatus: "납입 완료",
    },
    {
      name: "기초공사 완료",
      state: "완료",
      status: "complete",
      progress: 100,
      date: "2026.03.20 완료",
      guide: "기초공사 완료 기준 납입 회차가 처리되었습니다.",
      dueAmount: 96000000,
      paidAmount: 96000000,
      paymentStatus: "납입 완료",
    },
    {
      name: "골조 완료",
      state: "진행 중",
      status: "current",
      progress: 67,
      date: "2026.08.20 예정",
      guide: "현재 골조 공정 진행 중이며 다음 납부 회차가 예정되어 있습니다.",
      dueAmount: 96000000,
      paidAmount: 96000000,
      paymentStatus: "납입 완료",
    },
    {
      name: "벽체 완료",
      state: "예정",
      status: "upcoming",
      progress: 0,
      date: "2026.11.20 예정",
      guide: "벽체 완료 시점에 맞춰 납부 안내가 발송될 예정입니다.",
      dueAmount: 96000000,
      paidAmount: 0,
      paymentStatus: "납입 예정",
    },
    {
      name: "지붕 천장 완료",
      state: "예정",
      status: "upcoming",
      progress: 0,
      date: "2027.02.20 예정",
      guide: "상부 구조 마감 전후로 상세 안내가 제공됩니다.",
      dueAmount: 96000000,
      paidAmount: 0,
      paymentStatus: "납입 예정",
    },
    {
      name: "문 / 창호 / 전기 완료",
      state: "예정",
      status: "upcoming",
      progress: 0,
      date: "2027.05.20 예정",
      guide: "세대 내부 주요 설치 완료 후 확인 문서가 업데이트됩니다.",
      dueAmount: 96000000,
      paidAmount: 0,
      paymentStatus: "납입 예정",
    },
    {
      name: "입주 시",
      state: "대기",
      status: "waiting",
      progress: 0,
      date: "2027.08.31 예정",
      guide: "잔금, 키 수령, 입주 지정 기간 안내가 MY 알림에 표시됩니다.",
      dueAmount: 96000000,
      paidAmount: 0,
      paymentStatus: "납입 예정",
    },
  ],
  documentsAndNotices: [
    {
      kind: "문서",
      title: "공급계약서",
      date: "2025.10.30",
      summary: "계약 호 수, 계약일자, 납부 조건을 확인할 수 있는 원본 문서입니다.",
    },
    {
      kind: "문서",
      title: "계약금 영수증",
      date: "2025.11.01",
      summary: "8주 이내 계약금 납입 확인 영수증이 등록되었습니다.",
    },
    {
      kind: "공지",
      title: "중도금 대출 실행 안내",
      date: "2026.06.28",
      summary: "은행 방문 전 준비 서류와 담당자 연락처를 확인하세요.",
    },
    {
      kind: "문서",
      title: "마감재 선택 확인서",
      date: "2026.07.01",
      summary: "MY에 통합된 선택 마감 정보를 문서로 확인할 수 있습니다.",
    },
    {
      kind: "공지",
      title: "7월 현장 리포트 업데이트",
      date: "2026.07.02",
      summary: "공정 단계와 월간 현장 안내가 Journey에 반영되었습니다.",
    },
    {
      kind: "공지",
      title: "입주 설명회 안내",
      date: "2026.07.03",
      summary: "사전점검, 키 수령, 입주 절차 안내 일정이 공개되었습니다.",
    },
  ],
  myPanels: {
    profile: {
      title: "내 정보",
      items: ["이름: KIM", "계약일자: 2025.10.30", "계약 호 수: 108동 2304호", "연락처: 010-2304-1080", "기본 정보: Timor Crest 계약자"],
    },
    contract: {
      title: "계약 / 서류",
      items: ["계약서: 공급계약서 등록 완료", "분양 관련 문서: 안내문 2건", "납부 관련 문서: 영수증 2건", "첨부 문서 목록: 계약서, 영수증, 마감재 선택 확인서"],
    },
    consult: {
      title: "상담",
      items: ["상담 신청 버튼: 분양 상담 예약", "최근 상담 내역: 중도금 대출 문의", "상담 상태: 답변 완료", "상담 날짜: 2026.07.02", "상담 내용 요약: 대출 실행 서류와 방문 일정 안내"],
      action: "상담 신청",
    },
    alerts: {
      title: "개인 알림",
      items: ["납부기간 도래: 중도금 3차 D-47", "사전점검 일정: 2027.07 예정", "키 수령방법 안내: 입주 지정 기간 전 공개", "계약 관련 안내: 마감재 선택 확인 필요", "문서 업데이트 안내: 7월 현장 리포트 등록"],
    },
  },
};
